### ISSUE TITLE
ShouldAllBeEquivalentTo/options.Including does not work with sub properties

### ISSUE THREAD

**Issue by Musashi178** [dennisdoomen/fluentassertions#278] opened 2015-06-29 14:03 UTC
I have a problem with the following test case

```csharp
using System;
using FluentAssertions;
using NUnit.Framework;

namespace FluentAssertionsTest
{
    [TestFixture]
    public class ShouldAllBeEquivalentToTests
    {
        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_an_array_with_equal_TestDummyObjects_but_with_only_a_subsub_property_included_should_not_throw()
        {
            var expectedObjects = new[]
                                  {
                                      new TestDummy(new SubDummy(12)),
                                      new TestDummy(new SubDummy(25)),
                                  };
            var actualObjects = new[]
                                {
                                    new TestDummy(new SubDummy(12)),
                                    new TestDummy(new SubDummy(25)),
                                };
            Action act = () => actualObjects.ShouldAllBeEquivalentTo(expectedObjects, options => options.Including(order => order.Sd.Id));
            act.ShouldNotThrow();
        }
    }

    public class SubDummy
    {
        private readonly int _id;

        public SubDummy(int id)
        {
            this._id = id;
        }

        public int Id
        {
            get { return this._id; }
        }

        public override bool Equals(object obj)
        {
            if (!(obj is SubDummy))
            {
                return false;
            }

            return this._id == ((SubDummy) obj)._id;
        }
    }

    public class TestDummy
    {
        private readonly SubDummy _sd;

        public TestDummy(SubDummy sd)
        {
            this._sd = sd;
        }

        public SubDummy Sd
        {
            get { return this._sd; }
        }
    }
}
```

I would expect the method not to throw as the equivalence check should only consider the property 'Id' of the property 'Sd'. 

Instead, I get the following AssertionException: 
> "Subject has item[0].Id that the other object does not have.
> Subject has item[1].Id that the other object does not have.
> 
> With configuration:
> - Use declared types and members
> - Compare enums by value
> - Select member FluentAssertionsTest.SubDummy.Id
> - Match member by name (or throw)
> - FluentAssertions.Equivalency.Ordering.CollectionMemberOrderingRuleDecorator
> "

Do I miss some option or is this a bug?

**Comment by dennisdoomen** [comment] 2015-06-29 14:11
Hi, which version of FA are you using?

**Comment by Musashi178** [comment] 2015-06-29 18:55
Hi, I am using the newest version 3.4.0.

**Comment by dennisdoomen** [comment] 2015-06-30 18:49
I can reproduce the issue. Trying to find the cause of it.

**Comment by dennisdoomen** [comment] 2015-07-01 18:01
So the problem is that FA doesn't support a nested property expression to include a nested object's property. It's not going to be trivial.

**Comment by dennisdoomen** [comment] 2015-07-03 18:54
Fixed in https://www.nuget.org/packages/FluentAssertions/3.4.1

**Closed by dennisdoomen** 2015-07-03 18:54 UTC
Labels: enhancement
