### ISSUE TITLE
ContainSingle failure does not include because reason

### ISSUE THREAD

**Issue by jon-armen** [dennisdoomen/FluentAssertions#425] opened 2016-06-21 14:55 UTC
I've written several assertions with \<collection>.Should().ContainSingle("because ..."); however the reason is never include with the assertion.

**Comment by dennisdoomen** [comment] 2016-06-21 18:09
Thanks for reporting @jarmen09. What is the type of the collection?

**Comment by jarmen09** [comment] 2016-06-21 18:16
Any type of collection, List<T> (i.e. List<int>), or from inheritance (i.e. class MyClass : List<int>)

**Comment by dennisdoomen** [comment] 2016-06-21 18:23
Which version of FA are you using? Because I can't reproduce that.

**Comment by jarmen09** [comment] 2016-06-21 18:37
Currently on 4.6.3.  I'll upgrade to 4.9.0 to see if that resolves.

**Comment by jarmen09** [comment] 2016-06-21 18:42
Here's my test code:

 [TestMethod]
        public void ContainSingleShouldContainBecauseStatement()
        {
            List\<int> collection = new List\<int>() { 1, 2 };
            collection.Should().ContainSingle("because a single item should be present");
        }

I would expect that my test would fail with a message similar to "Expected collection to contain a single item because a single item should be present.". However, my actual assertion is "Expected collection to contain a single item."

**Comment by jarmen09** [comment] 2016-06-21 18:45
The error seems like it might be coming from SelfReferencingCollectionAssertions.AndWhichConstraint\<TAssertions, T> ContainSingle(string because = "", params object[] becauseArgs).  Most of the methods in this class have the {reason} specified in the FailWith, however this method does not.

**Comment by dennisdoomen** [comment] 2016-06-21 18:57
I'll check. 4.6.3 is recent enough.

**Comment by dennisdoomen** [comment] 2016-06-23 19:42
Fixed in 4.9.1.

**Closed by dennisdoomen** 2016-06-23 19:42 UTC
Labels: bug
