### ISSUE TITLE
New signature: ShouldThrow(Type exceptionType...)

### ISSUE THREAD

**Issue by ewlloyd** [dennisdoomen/FluentAssertions#493] opened 2016-10-27 20:42 UTC
I propose a new, non-generic signature for ShouldThrow(), to allow (among other things) xUnit users to do something like this:

``` c#
    [Theory]
    [InlineData(typeof(ThisException), "this bogus data")]
    [InlineData(typeof(ThatException), "that bogus data")]
    public void TrulyExceptional(Type exceptionType, string bogusData)
    {
        Action inst = () => new ExceptionHurler(bogusData);
        inst.ShouldThrow(exceptionType);
    }
```

If there are no strenuous objections, I'll work it and put a PR together.

**Comment by somewhatabstract** [comment] 2016-11-07 06:19
This is a duplicate of https://github.com/dennisdoomen/FluentAssertions/issues/460

**Closed** 2016-11-07 06:57 UTC
Labels: duplicate, enhancement, up for grabs

**Comment by ewlloyd** [comment] 2016-11-07 07:04
I'll still see about that PR. It just got easier, though. :-)

**Comment by ewlloyd** [comment] 2016-11-07 07:04
I'll still see about that PR. It just got easier, though. :-)

On Nov 6, 2016 11:57 PM, "Dennis Doomen" <notifications@github.com> wrote:

Closed #493 <https://github.com/dennisdoomen/FluentAssertions/issues/493>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dennisdoomen/FluentAssertions/issues/493#event-849445738>,
or mute the thread
