### ISSUE TITLE
System.IO Exceptions in Windows 8.1 and Windows Phone 8.1 Unit Tests

### ISSUE THREAD

**Issue by AlexaHLE** [dennisdoomen/fluentassertions#311] opened 2015-11-20 15:50 UTC
In Projects for both Windows Phone Unit Test App, and Windows 8.1 Unit Test Library, FluentAssertions can be installed and the projects can be built, but the tests will fail with different Exceptions.

In Windows Phone 8.1, as soon as any FluentAssertions Method is called, The Test will fail immediately with the following:

>Result StackTrace:	at TestApp.WindowsPhone.WindowsPhoneTest.TestMethod1()
>Result Message:	Test method TestApp.WindowsPhone.WindowsPhoneTest.TestMethod1 threw exception: 
>System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

In Windows 8.1, The tests will run normally for any method (at least of those that I tried) except for ShouldBeEquivalentTo 

 >Result StackTrace:	
>at FluentAssertions.Common.TypeExtensions.HasProperties(Type type)
   at FluentAssertions.Common.TypeExtensions.IsComplexType(Type type) in C:\projects\fluentassertions-vf06b\Src\Core\Common\TypeExtensions.cs:line 131
   at FluentAssertions.Equivalency.ObjectReference.get_IsComplexType() in C:\projects\fluentassertions-vf06b\Src\Core\Equivalency\ObjectReference.cs:line 61
   at FluentAssertions.Equivalency.ObjectTracker.IsCyclicReference(ObjectReference reference) in C:\projects\fluentassertions-vf06b\Src\Core\Equivalency\ObjectTracker.cs:line 36
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\Core\Equivalency\EquivalencyValidator.cs:line 47
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\Core\Equivalency\EquivalencyValidator.cs:line 36
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, Func`2 config, String because, Object[] reasonArgs) in C:\projects\fluentassertions-vf06b\Src\Shared\AssertionExtensions.cs:line 610
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, String because, Object[] reasonArgs) in C:\projects\fluentassertions-vf06b\Src\Shared\AssertionExtensions.cs:line 572
   at TestApp.Windows.WindowsTest.TestMethod1() in C:\Users\alexa\Documents\Visual Studio 2015\Projects\FluentAssertionsTestApp\TestApp.Windows\WindowsTest.cs:line 21
>Result Message:	Test method TestApp.Windows.WindowsTest.TestMethod1 threw exception: 
>System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by dennisdoomen** [comment] 2015-11-20 17:19
Thanks for reporting this. What OS and Visual Studio version are you using?

**Comment by AlexaHLE** [comment] 2015-11-20 18:49
I am using Windows 8.1 Enterprise and Visual Studio 2015 version 14.0.23107.0

I also tried adding the packages specified in the errors with NuGet, but got errors about incompatible targets:

Windows 
>Could not install package 'System.Reflection.TypeExtensions 4.0.0'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Windows Phone
>Could not install package 'System.Runtime 4.0.20'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by dennisdoomen** [comment] 2015-11-21 09:27
Would you be able to send the project so I can try to reproduce it? I have a strong suspicion that you are missing a .NET patch or something. I'm running Windows 10 myself, so it's difficult for me to reproduce.

**Comment by AlexaHLE** [comment] 2015-11-24 15:17
I emailed the project to you. I'm using 4.0.1 on both targets.

**Comment by dennisdoomen** [comment] 2015-11-24 15:26
Thanks. I'll investigate.

**Comment by dennisdoomen** [comment] 2015-11-24 18:04
With your repo, I can finally reproduce it. But I don't have a clue what's going on here.

**Comment by dennisdoomen** [comment] 2015-11-24 18:33
OK, so the problem is that NuGet selects the wrong version of FluentAssertions. Instead of taking the assemblies from the `portable-win81+wpa81` folder, it picks the ones from the `dotnet` folder. I have no clue why that works like that, but maybe @onovotny can help here. He did the port to support .NET 4.6, Core CLR and .NET Native.

**Comment by onovotny** [comment] 2015-11-24 18:40
Unfortunately that's "correct" behavior. `dotnet` "wins" over any portable-* for any System.Runtime projects. That's Net45+, Wp8, wpa81, Xamarin, win8+, etc.

I think Xamarin's latest code should support those contracts...needs to be verified though.

The whole `dotnet` thing turned into a big mess. They are working on fixing yet by putting some sanity back...it'll be `netstandard` based:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

This will prevent older platforms from getting references that are too new for them.

For now, the fix is to duplicate the files in portable-win81+wpa81 into \lib\win81 and \lib\wpa81. A concrete platform will always "win" over `dotnet`.

**Comment by dennisdoomen** [comment] 2015-11-24 18:48
I will do that. Thanks for the quick response @onovotny.

**Comment by dennisdoomen** [comment] 2015-11-24 18:57
It seems that #295 is suffering from the same problem.

**Comment by dennisdoomen** [comment] 2015-11-24 19:07
One small question @onovotny. Is version `4.0.20` for `System.Runtime` correct [here](https://github.com/dennisdoomen/fluentassertions/blob/develop/Src/.nuspec#L49)?

**Comment by onovotny** [comment] 2015-11-24 19:12
Yes, that is correct. The "dotnet" versions are really ASPNet 5/Net46/Windows 10 (and up). Another way to look at them is actually being `netstandard1.3` based on that previous link.

Net4.5.1/Wpa81/Win81 would be `netstandard1.2`, which has a lower version it can use (4.0.10, I believe). That's the fundamental issue with `dotnet` and why it's broken. The workarounds are to duplicate specific TFM's and put the right things in there. A real pain.

**Comment by dennisdoomen** [comment] 2015-11-24 19:23
:+1:

**Comment by dennisdoomen** [comment] 2015-11-24 20:47
Should be fixed in 4.1

**Closed by dennisdoomen** 2015-11-24 20:47 UTC
