### ISSUE TITLE
Net40 FluentAssertions.Core dependency to mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

### ISSUE THREAD

**Issue by doubret** [dennisdoomen/FluentAssertions#379] opened 2016-03-23 18:16 UTC
The dependency to mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e is wrong when using FluentAssertions for .Net 4.0 projects.

It causes troubles to tools like postsharp that try to load the .NETPortable assembly.

Could you please change this so that it only references .NETFramework assemblies ?

**Comment by dennisdoomen** [comment] 2016-03-23 18:31
FA internally uses a PCL with the platform-independent stuff. That's by design and can't be changed unfortunately.

**Comment by doubret** [comment] 2016-03-23 18:40
Do you mean that it cannot work without PCL ?
Or it could be done but you don't plan to support it ?

Thanks

**Comment by dennisdoomen** [comment] 2016-03-23 18:42
No, I mean that FA is using a PCL library internally to share the logic between the different platforms it needs to support. This was a deliberate design decision.

**Comment by doubret** [comment] 2016-03-23 18:49
Ok, thanks for the clarification.
My problem is that i have a build server that doesn't have visual studio installed and therefore .NETPortable reference assemblies are not present.
Do you know a "clean" way to get reference assemblies for PCL installed on a continuous integration server ?
Maybe i can add PCL reference assemblies via a nuget package ?

**Comment by dennisdoomen** [comment] 2016-03-23 18:50
Maybe this helps? http://stackoverflow.com/questions/20518424/building-portable-class-library-project-in-build-server-fails

**Comment by doubret** [comment] 2016-03-23 18:56
I used this (wich is a bit cleaner) : https://blogs.msdn.microsoft.com/dotnet/2013/10/14/portable-class-library-pcl-now-available-on-all-platforms/

But still, i don't find it particulary clean to unzip and copy files manualy.
At least it works, thank you.

**Comment by dennisdoomen** [comment] 2016-03-31 19:04
So can we close this PR?

**Closed** 2016-04-16 07:53 UTC
