### ISSUE TITLE
ShouldAllBeEquivalentTo/options.Including does not work as expected

### ISSUE THREAD

**Issue by Musashi178** [dennisdoomen/fluentassertions#269] opened 2015-05-19 16:05 UTC
The test cases below describe an unexpected behavior when using ShouldAllBeEquivalentTo with the options.Including functionality. I would expect that `When_applying_ShouldAllBeEquivalentTo_to_an_array_with_different_B_but_with_only_A_included_it_should_not_throw` does not throw an expection, as it should only compare the items in the arrays by A, which are the same.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using NUnit.Framework;

namespace _2DIdent.Services.OrderManagementService.Tests
{
    public class FluentAssertionEnumerableEquivalencyTest
    {
        private static readonly Random Rnd = new Random((int) DateTime.Now.Ticks);

        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_an_array_with_different_B_but_with_B_excluded_it_should_not_throw()
        {
            var x = CreateManyTestDummies().ToArray();
            var y = x.Select(s => new TestDummy(s.A, s.B + 1)).ToArray();
            Action act = () => x.ShouldAllBeEquivalentTo(y, options => options.Excluding(i => i.B));
            act.ShouldNotThrow();
        }

        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_an_array_with_different_B_but_with_only_A_included_it_should_not_throw()
        {
            var x = CreateManyTestDummies().ToArray();
            var y = x.Select(s => new TestDummy(s.A, s.B + 1)).ToArray();
            Action act = () => x.ShouldAllBeEquivalentTo(y, options => options.Including(i => i.A));
            act.ShouldNotThrow();
        }

        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_an_array_with_different_B_it_should_throw()
        {
            var x = CreateManyTestDummies().ToArray();
            var y = x.Select(s => new TestDummy(s.A, s.B + 1)).ToArray();
            Action act = () => x.ShouldAllBeEquivalentTo(y);
            act.ShouldThrow<Exception>();
        }

        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_an_equal_array_it_should_not_throw()
        {
            var x = CreateManyTestDummies().ToArray();
            var y = x.Select(s => new TestDummy(s.A, s.B)).ToArray();
            Action act = () => x.ShouldAllBeEquivalentTo(y);
            act.ShouldNotThrow();
        }

        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_the_same_array_it_should_not_throw()
        {
            var x = CreateManyTestDummies().ToArray();
            var y = x;
            Action act = () => x.ShouldAllBeEquivalentTo(y);
            act.ShouldNotThrow();
        }

        public class TestDummy
        {
            private readonly int _a;
            private readonly int _b;

            public TestDummy(int a, int b)
            {
                this._b = b;
                this._a = a;
            }

            public int A
            {
                get { return this._a; }
            }

            public int B
            {
                get { return this._b; }
            }
        }

        private static IEnumerable<TestDummy> CreateManyTestDummies()
        {
            var numTestDummies = Rnd.Next(1, 10);

            for (var i = 0; i <= numTestDummies; ++i)
            {
                yield return new TestDummy(Rnd.Next(int.MaxValue - 1), Rnd.Next(int.MaxValue - 1));
            }
        }
    }
}

```

**Comment by dennisdoomen** [comment] 2015-05-28 19:05
This is duplicate of #245, which I already fixed on the `develop` branch.

**Closed by dennisdoomen** 2015-05-28 19:05 UTC
Labels: duplicate
