### ISSUE TITLE
Make null assertions compatible with Resharper

### ISSUE THREAD

**Issue by jotabe-net** [dennisdoomen/FluentAssertions#452] opened 2016-07-28 11:39 UTC
If I have an object that can be null, with an assertion like this:

`ObjectThatCanBeNull.Should().NotBeNull();`

and then I try to make an assertion like this:

`ObjectThatCanBeNull.Property.Should()...`

ReSharper shows an error because the code could be trying to access a property of a null object, and there is no way to tell ReSharper that we've already made that impossible with the first assertion.

Implementing an extension method decorated with an attribute like this solves the problem:

```
[ContractAnnotation("null => halt")]
public static AndConstraint<ObjectAssertions> ShouldBeNotNull(this object actualValue)
{
    return actualValue.Should().NotBeNull();
}
```

I think it would be interesting to include this method natively in FluenAssertions. However, I don't know if that is possible at all, or what is the reason for making the assertion in two function calls, instead of a single one. I understand that substituting the original `Should().BeNotNull()` would be a breaking change.

**Comment by somewhatabstract** [comment] 2016-11-07 05:52
Pertinent documentation

https://www.jetbrains.com/help/resharper/2016.1/Contract_Annotations.html
https://www.jetbrains.com/help/resharper/2016.1/Code_Analysis__Annotations_in_Source_Code.html
https://www.jetbrains.com/help/resharper/2016.1/Code_Analysis__Code_Annotations.html

**Comment by somewhatabstract** [comment] 2016-11-07 05:59
From what I can tell, since the `null` is being processed by the `Should()` but the ultimate decision of if the test continues is made by the `NotBeNull()`, there is no way to use the existing JetBrains annotations to tell its analysis engine not to flag subsequent dereferences of the value under test as possibly being null.

I am still investigating whether there is a way to extend the JetBrains analysis engine with any custom attribution that could achieve this.

**Comment by somewhatabstract** [comment] 2016-11-07 06:12
I do not believe this can be done.

**Comment by ulrichb** [comment] 2016-11-07 22:30
I also do not think that this is possible (with the current R# version) to bring this to `Should().NotBeNull()`.

Would you accept a new, additional `ShouldNotBeNull()` which would allow to add the R# annotation?

**Comment by somewhatabstract** [comment] 2016-11-07 22:34
@ulrichb: My personal opinion is that such a change would create confusion in the API usage. There would be multiple ways to define the same thing with the only difference being support for R#. I think I'd rather users had to add an R# comment to their files to exempt offending lines from the blue squigglies than make such a change to the FluentAssertions library.

**Comment by jotabe-net** [comment] 2016-11-08 00:30
The comments solution is not practical: too many comments.
I tried hard to find a way to do it with R#, but I think it's not possible.
In my VS solutions I have an static class with the aforementioned extension methods, which I copy from project to project.
So a possible solution would be to create a separate Nuget package to make it easier to add support for R# users without interfering with other users.
I don't know if Roslyn could help in any way.

**Comment by petermorlion** [comment] 2016-11-10 09:27
FYI: it is possible to add annotations without changing the dll, using [External Annotations](https://www.jetbrains.com/help/resharper/2016.2/Code_Analysis__External_Annotations.html), but like @somewhatabstract says, because of how `Should()` and `NotBeNull()` work, I don't think they're any use.

**Comment by jotabe-net** [comment] 2016-11-11 01:27
I think my comment wasn't clear enough. I think it would be possible to create a Nuget package which included ’ShouldBeNull’ and similar methods which can be decorated with R# attributes.

This package could ne named domething like 'FluentAssertions.ResharperSupport'. In this way the additional methods would only be available if someone really wanted to use them. 

Another option would be to include these methods in a nested namespace, so that they would only be available if the required ‘using’ was specified.

With these solutions, the extra extension methods would only be available if explicitly included by the programmer, making things easier for R# users, without disturbing other users

**Comment by dennisdoomen** [comment] 2016-11-11 16:57
Considering all the discussions above (and thanks for the investigation work guys), I've concluded that supporting this is not going to be possible without introducing significant breaking changes in the API. So I think it is safe to close the issue. Thoughts?

**Comment by somewhatabstract** [comment] 2016-11-11 17:31
While a completely separate nuget package would help avoid API polution, it would introduce a new API that doesn't really fit with the paradigm of FluentAssertions and would also be very specific to one developer tool. Since the information R# adds to the IDE is only guidance, I don't see that this is necessary. Only the OCD within us wants all squigglies gone in this sort of situation. If this were production code, I'd be more for it, but it's test code and those writing tests using FluentAssertions would surely be aware of how it works and that there is really no error.

With all that said, I agree @dennisdoomen that this isn't something we should tackle.

**Comment by petermorlion** [comment] 2016-11-11 23:15
I can definitely live with that. Closing the issue is fine by me. Also, a Nuget package might be overkill for this one issue (don't know if there are any others). You could easily write this on a per-project basis.

**Comment by dennisdoomen** [comment] 2016-11-12 06:51
Closing per discussion

**Closed by dennisdoomen** 2016-11-12 06:51 UTC
Labels: won't fix

**Comment by kcragin** [comment] 2021-01-15 14:27
I came here looking for the compatibility between Fluent Assertions and ReSharper as well. For those that are ok with a workaround this at least avoids the squiggles if placed prior to other assertions:

```
Debug.Assert(expression != null)
```

If you don't like that, you can write

```
// no warning here
expression.NonNull().Property.Should().Etc...
```

if you use an extension method like

```
[JetBrains.Annotations.NotNull]
public static  T NonNull<T>(this T subject) where T : class
{
    subject.Should().NotBeNull();
    return subject;
}
```

Unfortunately if you have to apply assertions using `expression` many times, the second--Nth usages will bring back the squiggles. You can avoid that as well if your expression can be assigned to, but you'd have to use this (admittedly tortured) syntax:

```
// no warning here
(expression = expression.NonNull()).Property.Should().Etc...
// no warning here
expression.OtherProperty.Should().Etc...
```

Not pretty, but there if you want it.
